### ISSUE TITLE
Dark GTK theme is hard to read

### ISSUE THREAD

**Issue by MartinX3** [masneyb/gftp#115]
The colorful output is hard to read on black ground.

![grafik](https://user-images.githubusercontent.com/4518092/123103364-36582180-d436-11eb-9bc0-e4827d27966f.png)

**Comment by wdlkmpx** [comment]
I don't know how to detect dark mode programmatically and change colors accordingly, but it's possible to disable colors with a setting, and maybe the colored output should be disabled by default?

A new item under the FTP menu?: Enable colors in log, a GtkCheckMenuItem

![sc](https://user-images.githubusercontent.com/10052849/140402127-369dac88-1f48-4105-bdad-cfb0a99e3fa3.png)

**Comment by wdlkmpx** [comment]
Menu `gFTP -> Colored messages`, I'm not sure about the word, but we're talking about text, corrections are welcome

Ctrl+Alt+C
![Screenshot(4)](https://user-images.githubusercontent.com/10052849/140584742-51451ebc-4350-4cea-9c7d-1df779f42af5.png)
