### ISSUE TITLE
Should use MLSD command when the server supports it

### ISSUE THREAD

**Issue by falemagn** [masneyb/gftp#120]
Hi,

gFTP currently uses the LIST command to retrieve directory contents, but appends to it non-standard "parameters", such as -aL: this breaks those servers that abide by the letter of the RFC and stops working on all the other servers the moment a file/directory named "-aL" exists in the current working directory. gFTP should probably at least retry to issue LIST **without** the appended "-aL" options, when that command fails.

However, most of the FTP servers nowadays support the MLSD command, standardized by [RFC 3659](https://datatracker.ietf.org/doc/html/rfc3659#page-23), and I believe gFTP should use that for directory listing, only falling back to LIST if MLSD is not supported.

**Comment by wdlkmpx** [comment]
There is a way to know if the server supports MLSD, with the `FEAT` command ( https://datatracker.ietf.org/doc/html/rfc2389 )

I'll try to add code to parse the response and set flags, variables, etc. to modify the client behavior according to that info.

`OPTS LIST` should provide info about the params accepted by LIST, but I always get error 501

```
Connected to localhost:21
220 (vsFTPd 3.0.3)
211-Features:
 AUTH SSL
 AUTH TLS
 EPRT
 EPSV
 MDTM
 PASV
 PBSZ
 PROT
 REST STREAM
 SIZE
 TVFS
211 End
```

```
Looking up ftp.freebsd.org
FEAT
211-Features:
 EPRT
 EPSV
 MDTM
 PASV
 REST STREAM
 SIZE
 TVFS
 UTF8
211 End
```

```
ftp.bit.nl
211-Features:
 UTF8
 EPRT
 SITE SYMLINK
 EPSV
 SITE UTIME
 MDTM
 SITE RMDIR
 TVFS
 MFMT
 LANG en-US.UTF-8*;en-US
 SIZE
 SITE MKDIR
 MFF modify;UNIX.group;UNIX.mode;
 REST STREAM
 MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.mode*;UNIX.owner*;
211 End
```

**Comment by wdlkmpx** [comment]
**MLSD (MLST) support has been implemented and is used when available**
LIST -al is used when MLSD is not supported by the server... 

Gftp will fall back to LIST if an error response is received

So far all servers behave as expected, `MLSD`: ok, `LIST -al` ok

(`LIST`: All FTP servers seem to ignore -L (dereference symlink), there must be a reason for that)
