### ISSUE TITLE
Implicit TLS/SSL

### ISSUE THREAD

**Issue by wdlkmpx** [masneyb/gftp#127]
https://www.smartftp.com/en-us/support/kb/189

> **FTP over TLS (Explicit).** Explicit security requires that the FTP client issues a specific command to the FTP server after establishing a connection to establish the SSL link. In explicit TLS the FTP client needs to send an explicit command (i.e. "AUTH TLS") to the FTP server to initiate a secure control connection. The default FTP server port is used. This formal method is documented in RFC 4217.

> **FTP over TLS (Implicit) - Deprecated** Implicit security is a mechanism by which security is automatically turned on as soon as the FTP client makes a connection to an FTP server. In this case, the FTP server defines a specific port for the client (990) to be used for secure connections. FTP over TLS Implicit has been deprecated and should no longer be used.

Currently gFTP doesn;'t support Implicit SSL.
It should be identified as a different protocol. I think FileZilla uses something like this:
- FTPS (ftps://) - Implicit SSL
- FTPES (ftpes://) - Explicit SSL

That would explain why @hk3f is unable to connect to a filezilla server with gftp.

However in gFTP:
- FTPS (ftps://) = Explicit SSL (TLS)

and the new protocol should be something like this:
- FTPSi (ftpsi://) = Implicit SSL (TLS)

**Comment by wdlkmpx** [comment]
This has been implemented, @h3kf you can test now

**Comment by hk3f** [comment]
Worked fine in my local FTPS server.
