### ISSUE TITLE
FTP Category Server Manager

### ISSUE THREAD

**Issue by ajung2** [masneyb/gftp#151]
Hello, would you like to add a server manager tree like FileZilla, where we can categorize our FTP connections?

**Comment by wdlkmpx** [comment]
That sounds like a good idea, but the `Bookmarks->Edit bookmarks` dialog implements something like that,  not as sophisticated 

Hmmm
![image](https://user-images.githubusercontent.com/10052849/220216850-3c8ed02c-14ec-48f0-a17f-4f7f3c4eea02.png)

Right now I'm trying to use Filezilla through Wine to see how it works, but I can't close the dialog to update the app, have to kill it

**Comment by ajung2** [comment]
It was not easy to figure out how to save the connection as a bookmark. Thank you very much!
