### ISSUE TITLE
large size files bug

### ISSUE THREAD

**Issue by antitoxine** [masneyb/gftp#66]
![gftp-2 0 19](https://user-images.githubusercontent.com/64896914/82119643-7dc6a580-9780-11ea-8dc2-0ae4be7f1709.png)

gftp 2.0.19-5
in ssh2 connection to my website

I notice that the value of large files larger than 20 GB is wrong 

I have a big planet.bin file (30 GB) on my site
this is one openstreetmap navit map
36213412764 bytes

When i make ssh2 connection with gftp, the file size is on remote site
1853674396 bytes (that's false)

When i make ssh2 connection with filezilla, the file size is on remote site
36213412764 bytes (that's right)

you can see the picture

**Comment by apkrieg** [comment]
@antitoxine, can gFTP download the file correctly? I'm wondering if this is just a GUI issue before I dive into the source.

**Comment by wdlkmpx** [comment]
PR https://github.com/masneyb/gftp/pull/67 fixes the bug.

The function to fix was `sshv2_buffer_get_int64()`. The logic, I can't explain it. It just happened, as you can see, the screenshot shows even a correct date in the sshv2 listbox
![sftp](https://user-images.githubusercontent.com/10052849/85087043-ed600280-b20e-11ea-891f-245904a4da0f.png)

**Comment by apkrieg** [comment]
Awesome work.
