### ISSUE TITLE
RFCs non-distributable

### ISSUE THREAD

**Issue by gusnan** [masneyb/gftp#95]
Is there any chance to remove the RFCs from the package archive (and git)? Would it be reasonable to have them only linked, instead of included?

I am working on the Debian package of gftp, and notice that the rfcs are non-distributable in Debian main. The lintian tool (a Debian package checker that reports common problems) reports that 4 of the rfcs shouldn't be included in Debian main:

```
E: gftp source: license-problem-non-free-RFC docs/rfcs/draft-ietf-secsh-filexfer-04.txt
N: 
N:    The given source file is licensed under the newer RFC license.
N:    
N:    The majority of IETF documents, such as RFCs, are not licensed under
N:    DFSG-free terms, and should thus not be included in Debian main.
N:    
N:    If this file is multi-licensed, please override the tag.
N:    
N:    Refer to https://wiki.debian.org/NonFreeIETFDocuments for details.
N:    
N:    Severity: error
N:    
N:    Check: cruft
N: 
E: gftp source: license-problem-non-free-RFC docs/rfcs/draft-murray-auth-ftp-ssl-09.txt
E: gftp source: license-problem-non-free-RFC docs/rfcs/rfc2246.txt
E: gftp source: license-problem-non-free-RFC docs/rfcs/rfc2428.txt
```
If they are dual-licensed, please excuse my ignorance, but I haven't found any information about that in the package.

**Comment by wdlkmpx** [comment]
The rfcs were deleted. Now release tarballs will be a bit smaller...

Links to online RFCs
https://github.com/masneyb/gftp/wiki/RFCs

**Comment by gusnan** [comment]
Great! Thank you very much for making it this simple.
