### ISSUE TITLE
Follow XDG Base Directory Specification and more

### ISSUE THREAD

**Issue by aintyourcat** [masneyb/gftp#99]
Hello! Thanks for the app. Just a little suggestion from my personal preference, instead of making a directory in ~, it will be better if you could follow the XDG Base Directory specification (https://wiki.archlinux.org/index.php/XDG_Base_Directory), so we can put the user configuration on $XDG_CONFIG_HOME and the cache on $XDG_CACHE_HOME. 

![port-field-too-small](https://user-images.githubusercontent.com/66950307/96326390-b7495880-101f-11eb-89a9-a30ce333fa7d.gif)

Next, I've found that the port field (on top) is too small, even when i resize the window, it seems that it isn't resizeable. And the last one, the log text is not readable with my Dracula theme, is there any option to change the color?

**Comment by wdlkmpx** [comment]
I was planning to do that, I guess it's something easy to do, but it will change the config file location. I've been using Windows XP for a few weeks now, but here the new possible file locations:

XDG_CONFIG_HOME = $HOME/.config

```
$HOME/.config/gftp/gftprc
$HOME/.config/gftp/bookmarks
$HOME/.config/gftp/etc ...
```

XDG_CONFIG_DIRS = /etc

`/etc/gftprc`

Here's a gtk2 test dialog that somehow references XDG_CONFIG_HOME, but it's not used...

```c
	GtkWidget * label = gtk_label_new ("");
	GtkWidget * label2 = gtk_label_new ("");
	char * p, * localConfigDir;
#ifdef __MINGW32__
	p = strrchr (argv[0], '\\');
	localConfigDir = getenv ("LOCALAPPDATA");
	if (!localConfigDir) {
		localConfigDir = getenv ("APPDATA");
	}
#else
	p = strrchr (argv[0], '/');
	localConfigDir = getenv ("XDG_CONFIG_HOME");
#endif
	if (p) *p = 0;
	if (localConfigDir) {
		gtk_label_set_label (GTK_LABEL (label), localConfigDir);
	}
	gtk_label_set_label (GTK_LABEL (label2), argv[0]);
```

![](https://i.ibb.co/LpHXL47/2020-11-27-213008.png)

**Comment by wdlkmpx** [comment]
All the issues you reported have been fixed I think
